services:
  vibe-os:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
